# Generated by Django 3.0.5 on 2020-06-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200609_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='type',
        ),
        migrations.AlterField(
            model_name='plan',
            name='annual_discount',
            field=models.IntegerField(),
        ),
    ]
